version: "3.9"

x-common-environment-networks: &common-environment-networks
  env_file: .env
  networks:
    - app-network

x-api-service-build: &api-service-build
  build:
    context: .
    dockerfile: ./apps/api/Dockerfile

x-common-logging: &common-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

services:
  dashboard:
    build:
      context: .
      dockerfile: ./apps/dashboard/Dockerfile
    <<: *common-environment-networks
    <<: *common-logging
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://dashboard:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    <<: *common-environment-networks
    <<: *common-logging
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://frontend:3001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    <<: [*api-service-build, *common-environment-networks, *common-logging]
    restart: unless-stopped
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - db
      - redis
      - typesense
    healthcheck:
      test: ["CMD", "php", "artisan", "octane:status"]
      interval: 30s
      timeout: 10s
      retries: 3
    extra_hosts:
      - "${API_DOMAIN:-api.test.local}:host-gateway"

  horizon:
    <<: [*api-service-build, *common-environment-networks, *common-logging]
    restart: unless-stopped
    environment:
      CONTAINER_MODE: horizon
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "php", "artisan", "horizon:status"]
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler:
    <<: [*api-service-build, *common-environment-networks, *common-logging]
    restart: unless-stopped
    environment:
      CONTAINER_MODE: scheduler
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "php", "artisan", "schedule:list"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    <<: *common-environment-networks
    <<: *common-logging
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.2
    <<: *common-environment-networks
    <<: *common-logging
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3

  typesense:
    image: typesense/typesense:26.0
    <<: *common-environment-networks
    <<: *common-logging
    restart: unless-stopped
    command: --data-dir /data --api-key=${TYPESENSE_API_KEY} --listen-port ${TYPESENSE_PORT} --enable-cors
    volumes:
      - typesense_data:/data
    ports:
      - "${TYPESENSE_PORT:-8108}:8108"

  cube_api:
    restart: always
    image: cubejs/cube:latest
    ports:
      - 4000:4000
    environment:
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_DB_HOST=db
      - CUBEJS_DB_NAME=${MYSQL_DATABASE}
      - CUBEJS_DB_USER=${MYSQL_USER}
      - CUBEJS_DB_PASS=${MYSQL_PASSWORD}
      - CUBEJS_DB_EXPORT_BUCKET=cubestore
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_API_SECRET=secret
    volumes:
      - ./cube:/cube/conf
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
    networks:
      - dev-network

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:latest
    environment:
      - CUBEJS_DB_TYPE=mysql
      - CUBEJS_DB_HOST=db
      - CUBEJS_DB_NAME=${MYSQL_DATABASE}
      - CUBEJS_DB_USER=${MYSQL_USER}
      - CUBEJS_DB_PASS=${MYSQL_PASSWORD}
      - CUBEJS_DB_EXPORT_BUCKET=cubestore
      - CUBEJS_CUBESTORE_HOST=cubestore_router
      - CUBEJS_API_SECRET=secret
      - CUBEJS_REFRESH_WORKER=true
    volumes:
      - ./cube:/cube/conf
    networks:
      - dev-network
 
  cubestore_router:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_PORT=9999
      - CUBESTORE_SERVER_NAME=cubestore_router:9999
    volumes:
      - ./cube/.cubestore:/cube/data
    networks:
      - dev-network
 
  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      - CUBESTORE_WORKERS=cubestore_worker_1:10001
      - CUBESTORE_SERVER_NAME=cubestore_worker_1:10001
      - CUBESTORE_WORKER_PORT=10001
      - CUBESTORE_REMOTE_DIR=/cube/data
      - CUBESTORE_META_ADDR=cubestore_router:9999
    volumes:
      - ./cube/.cubestore:/cube/data
    depends_on:
      - cubestore_router
    networks:
      - dev-network

volumes:
  mysql_data:
  typesense_data:
  tmpfiles:
    driver: local

networks:
  app-network:
    driver: bridge