version: "3.9"

services:
  db-dev:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - dev-network

volumes:
  mysql_data:

networks:
  dev-network:
    driver: bridge
