version: '3.9'

services:
  api-dev:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ./apps/api/.env.development
    volumes:
      - ./apps/api:/var/www
    depends_on:
      - db-dev

  db-dev:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql # Persist data
    ports:      
      - "${DB_PORT:-3307}:3306"

volumes:
  mysql_data:
