FROM nginx:alpine

# Copy nginx configuration template
COPY nginx.tmpl /etc/nginx/conf.d/nginx.conf.template

# Copy the start script
COPY start-nginx.sh /start-nginx.sh

# Make the start script executable
RUN chmod +x /start-nginx.sh

# Set the command to run the start script
CMD ["/start-nginx.sh"]