cubes:
  - name: product_show
    sql_table: homestead.product_show
    data_source: default

    joins:
      - name: shows
        sql: "{CUBE}.show_id = {shows}.id"
        relationship: many_to_one

      - name: products
        sql: "{CUBE}.product_id = {products}.id"
        relationship: many_to_one

    dimensions:
      - name: id
        sql: id
        type: number
        primary_key: true

    measures:
      - name: count
        type: count

      - name: amount
        sql: amount
        type: sum

      - name: adjusted_price
        sql: adjusted_price
        type: sum

    pre_aggregations:
      # Pre-aggregation definitions go here.
      # Learn more in the documentation: https://cube.dev/docs/caching/pre-aggregations/getting-started

